# Generated by Django 4.0 on 2021-12-17 17:03

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(max_length=1000)),
                ('immagine', models.ImageField(upload_to='')),
                ('prezzo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('categoria', models.CharField(choices=[('A', 'Abbigliamento e Scarpe'), ('B', 'Accessori'), ('C', 'Casalinghi'), ('L', 'Console e Videogiochi'), ('E', 'Elettronica'), ('F', 'Ferramenta'), ('D', 'Fiori e Piante'), ('G', 'Giocattoli'), ('H', 'Hobbistica'), ('I', 'Informatica'), ('N', 'Libri e Cultura'), ('M', 'Sport')], max_length=20)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('condizione', models.CharField(choices=[('N', 'Nuovo'), ('U', 'Usato'), ('R', 'Rotto'), ('A', 'Altro - Pezzi di ricambio')], max_length=2)),
                ('luogo', models.CharField(max_length=30)),
                ('CAP', models.CharField(max_length=5)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ordinato', models.BooleanField(default=False)),
                ('acquirente', models.CharField(blank=True, max_length=50, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(max_length=30)),
                ('città', models.CharField(max_length=30)),
                ('cap', models.CharField(max_length=5)),
                ('via', models.CharField(max_length=50)),
                ('interno', models.CharField(blank=True, max_length=30)),
                ('note', models.TextField(blank=True)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='RecommendedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_item', models.PositiveIntegerField(default=0)),
                ('condizioneN', models.PositiveIntegerField(default=0)),
                ('condizioneU', models.PositiveIntegerField(default=0)),
                ('condizioneO', models.PositiveIntegerField(default=0)),
                ('prezzo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sum_prezzo', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Recommended Item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recommended', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shippingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
